HitExercise.MVC/Models/ViewModels/SupplierViewModel.cs
using HitExercise.DataAccess.Core.Entities;
using HitExercise.MVC.Models.Dtos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HitExercise.MVC.Models.ViewModels
{
    public class SupplierViewModel
    {
        public SupplierDto Supplier { get; set; }

        public List<SupplierCategory> Categories { get; set; }

        public List<Country> Countries { get; set; }


    }
}

HitExercise.MVC/Controllers/API/SuppliersController.cs
using AutoMapper;
using HitExercise.DataAccess.Core.Entities;
using HitExercise.DataAccess.Core.Interfaces;
using HitExercise.DataAccess.HelperClasses;
using HitExercise.MVC.Models.Dtos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Helpers;
using System.Web.Http;

namespace HitExercise.MVC.Controllers.API
{
    
    public class SuppliersController : ApiController
    {
        private readonly IDataAccess _dataAccess;

        public SuppliersController(IDataAccess dataAccess)
        {
            _dataAccess = dataAccess;
        }

        //Get All
        [HttpGet]
        public IHttpActionResult GetSuppliers()
        {
            var suppliers = _dataAccess
                .Suppliers
                .GetAll()
                .Select(Mapper.Map<Supplier,SupplierDto>);

            return Ok(suppliers);
        }

        //Get with ID
        [HttpGet]
        public IHttpActionResult GetSupplier(int id)
        {
            var supplier = _dataAccess.Suppliers.GetById(id);

            if (supplier == null)
                return NotFound();

            return Ok(Mapper.Map<Supplier,SupplierDto>(supplier));
        }

        //Create
        [HttpPost]
        public IHttpActionResult AddSupplier(SupplierDto supplierDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            
            if (!MyValidation.ValidateSupplier(supplierDto.Id,supplierDto.Afm,supplierDto.Name,_dataAccess))
                return BadRequest("Supplier is not Valid");

            var supplier = Mapper.Map<SupplierDto, Supplier>(supplierDto);


            _dataAccess.Suppliers.Create(supplier);
            _dataAccess.Complete();

            

            return Created(new Uri(Request.RequestUri + "/" + supplier.Id),supplierDto);
        }

        //Edit
        [HttpPut]
        public IHttpActionResult UpdateSupplier(int id, SupplierDto supplierDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var supplierInDb = _dataAccess.Suppliers.GetById(id);

            if (supplierInDb == null)
                return NotFound();
            
            if (!MyValidation.ValidateSupplier(supplierDto.Id,supplierDto.Afm,supplierDto.Name, _dataAccess))
                return BadRequest("Supplier is not Valid");

            supplierDto.Category = _dataAccess.Categories.GetById(supplierDto.CategoryId);
            supplierDto.Country = _dataAccess.Countries.GetById(supplierDto.CountryId);
            
            

            Mapper.Map(supplierDto, supplierInDb);


            _dataAccess.Complete();

            return StatusCode(HttpStatusCode.NoContent);
        }

        //Delete
        [HttpDelete]
        public IHttpActionResult DeleteSupplier(int id)
        {
            var supplierInDb = _dataAccess.Suppliers.GetById(id);

            if (supplierInDb == null)
                return NotFound();

            _dataAccess.Suppliers.Delete(id);
            _dataAccess.Complete();

            return Ok(supplierInDb);
        }
    }
}

HitExercise.MVC/Controllers/SuppliersController.cs
using AutoMapper;
using HitExercise.DataAccess.Core.Entities;
using HitExercise.DataAccess.Core.Interfaces;
using HitExercise.MVC.HelperClasses;
using HitExercise.MVC.Models.Dtos;
using HitExercise.MVC.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace HitExercise.MVC.Controllers
{
    [Authorize]
    public class SuppliersController : Controller
    {
        private readonly IDataAccess _dataAccess;

        public SuppliersController(IDataAccess dataAccess)
        {
            _dataAccess = dataAccess;
        }
        // GET: Suppliers
        public ActionResult Index()
        {
            var supplierViewModel = new SupplierViewModel()
            {
                Categories = _dataAccess.Categories.GetAll().ToList(),
                Countries = _dataAccess.Countries.GetAll().ToList()
            };
            return View(supplierViewModel);
        }

        [HttpPost]
        public ActionResult Add(SupplierViewModel supplierViewModel)
        {
            var supplierDto = supplierViewModel.Supplier;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44301/api/");
                var postTask = client.PostAsJsonAsync<SupplierDto>("suppliers/", supplierDto);
                postTask.Wait();

                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var email = new SendEmail();
                    email.SendEmailToSupplier(supplierDto);
                    supplierViewModel.Supplier = new SupplierDto();
                    return RedirectToAction("index");
                }
            }
            supplierViewModel.Categories = _dataAccess.Categories.GetAll().ToList();
            supplierViewModel.Countries = _dataAccess.Countries.GetAll().ToList();
            return View("Index",supplierViewModel);
        }
        
        
        public ActionResult Edit(int id)
        {
            //using the Api to get supplier using id
            var supplier = new Supplier();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44301/api/");

                var readData = client.GetAsync($"suppliers/{id}");
                readData.Wait();

                var resultData = readData.Result;

                //if the api call is not successful
                if (!resultData.IsSuccessStatusCode)
                {
                    return HttpNotFound();

                }

                var data = resultData.Content.ReadAsAsync<Supplier>();
                data.Wait();
                supplier = data.Result;
            }   
            //automap supplierfromdb to supplierDto
            var supplierDto = Mapper.Map<Supplier, SupplierDto>(supplier);

            var supplierViewModel = new SupplierViewModel()
            {
                Supplier = supplierDto,
                Categories = _dataAccess.Categories.GetAll().ToList(),
                Countries = _dataAccess.Countries.GetAll().ToList()
            };
            return View(supplierViewModel);
        }

        [HttpPost]
        public ActionResult Edit(SupplierViewModel supplierViewModel)
        {
            var supplierDto = supplierViewModel.Supplier;
            
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44301/api/");
                var putTask = client.PutAsJsonAsync<SupplierDto>($"suppliers/{supplierDto.Id}",supplierDto);
                putTask.Wait();

                var result = putTask.Result;
                if (result.IsSuccessStatusCode)
                    return RedirectToAction("index");               

            }
            supplierViewModel = new SupplierViewModel()
            {
                Supplier = supplierDto,
                Categories = _dataAccess.Categories.GetAll().ToList(),
                Countries = _dataAccess.Countries.GetAll().ToList()
            };
            return View(supplierViewModel);
        }




    }
}

HitExercise.MVC/Views/Suppliers/Edit.cshtml
@model HitExercise.MVC.Models.ViewModels.SupplierViewModel

@{
    ViewBag.Title = "Edit";
}
@Styles.Render("~/Content/css")
<h2>Edit Supplier</h2>


@using (Html.BeginForm("Edit", "Suppliers", FormMethod.Post, new { @class = "edit-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Supplier.Id, new { id = "getId" })

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier.Name, htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Supplier.Name, new { htmlAttributes = new { @class = "form-control", id = "getName" } })
                @Html.ValidationMessageFor(model => model.Supplier.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier.CategoryId, "Category", htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-5">
                @Html.DropDownListFor(model => model.Supplier.CategoryId, new SelectList(Model.Categories, "Id", "Title"), new { @class = "form-control", @id = "getCategory" })
                @Html.ValidationMessageFor(model => model.Categories, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier.Afm, htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Supplier.Afm, new { htmlAttributes = new { @class = "form-control", id = "getAfm" } })
                @Html.ValidationMessageFor(model => model.Supplier.Afm, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier.Address, htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Supplier.Address, new { htmlAttributes = new { @class = "form-control", id = "getAddress" } })
                @Html.ValidationMessageFor(model => model.Supplier.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier.Telephone, htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Supplier.Telephone, new { htmlAttributes = new { @class = "form-control", id = "getTelephone" } })
                @Html.ValidationMessageFor(model => model.Supplier.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier.Email, htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.Supplier.Email, new { htmlAttributes = new { @class = "form-control", id = "getEmail" } })
                @Html.ValidationMessageFor(model => model.Supplier.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier.CountryId, "Country", htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-5">
                @Html.DropDownListFor(model => model.Supplier.CountryId, new SelectList(Model.Countries, "Id", "Name"), new { @class = "form-control", @id = "getCountry" })
                @Html.ValidationMessageFor(model => model.Countries, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier.Inactive, htmlAttributes: new { @class = "control-label col-md-5" })
            <div class="col-md-5">
                @Html.CheckBoxFor(model => model.Supplier.Inactive, new { htmlAttributes = new { id = "getInactive" } })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-5 col-md-5">
                <input type="submit" id="edit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/lib")
    @Scripts.Render("~/bundles/InactiveSup")

    

}

HitExercise.MVC/Views/Suppliers/Index.cshtml
@model HitExercise.MVC.Models.ViewModels.SupplierViewModel

@{
    ViewBag.Title = "Supplier List";
}

<h2>Index</h2>

<p>
    <button type="button" class="btn btn-primary" id="test" data-toggle="modal" data-target="#supplierModal">
        <i class="fas fa-plus"></i> Add New
    </button>
</p>




@*-------------- Add New MODAL START--------------------------*@

<div class="modal fade" id="supplierModal" role="dialog" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Add New Supplier</h2>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Add", "Suppliers", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">


                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Supplier.Name, htmlAttributes: new { @class = "control-label col-md-5 " })
                            <div class="col-md-5">
                                @Html.EditorFor(model => model.Supplier.Name, new { htmlAttributes = new { @class = "form-control", @id = "getName" } })
                                @Html.ValidationMessageFor(model => model.Supplier.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Supplier.CategoryId, "Category", htmlAttributes: new { @class = "control-label col-md-5" })
                            <div class="col-md-5">
                                @Html.DropDownListFor(model => model.Supplier.CategoryId, new SelectList(Model.Categories, "Id", "Title"), "Select Category", new { @class = "form-control", @id = "getCategory" })
                                @Html.ValidationMessageFor(model => model.Supplier.CategoryId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Supplier.Afm, htmlAttributes: new { @class = "control-label col-md-5" })
                            <div class="col-md-5">
                                @Html.EditorFor(model => model.Supplier.Afm, new { htmlAttributes = new { @class = "form-control", @id = "getAfm" } })
                                @Html.ValidationMessageFor(model => model.Supplier.Afm, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Supplier.Address, htmlAttributes: new { @class = "control-label col-md-5" })
                            <div class="col-md-5">
                                @Html.EditorFor(model => model.Supplier.Address, new { htmlAttributes = new { @class = "form-control", @id = "getAddress" } })
                                @Html.ValidationMessageFor(model => model.Supplier.Address, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Supplier.Telephone, htmlAttributes: new { @class = "control-label col-md-5" })
                            <div class="col-md-5">
                                @Html.EditorFor(model => model.Supplier.Telephone, new { htmlAttributes = new { @class = "form-control", @id = "getTelephone" } })
                                @Html.ValidationMessageFor(model => model.Supplier.Telephone, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Supplier.Email, htmlAttributes: new { @class = "control-label col-md-5" })
                            <div class="col-md-5">
                                @Html.EditorFor(model => model.Supplier.Email, new { htmlAttributes = new { @class = "form-control", @id = "getEmail" } })
                                @Html.ValidationMessageFor(model => model.Supplier.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Supplier.CountryId, "Country", htmlAttributes: new { @class = "control-label col-md-5" })
                            <div class="col-md-5">
                                @Html.DropDownListFor(model => model.Supplier.CountryId, new SelectList(Model.Countries, "Id", "Name"), "Select Country", new { @class = "form-control", @id = "getCountry" })
                                @Html.ValidationMessageFor(model => model.Supplier.CountryId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Supplier.Inactive, htmlAttributes: new { @class = "control-label col-md-5" })
                            <div class="col-md-5">
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Supplier.Inactive, new { @id = "getInactive" })
                                    @Html.ValidationMessageFor(model => model.Supplier.Inactive, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-offset-6">
                            <button type="submit" class="btn btn-primary " id="save">Save Supplier</button>
                            <button type="reset" class="btn btn-default ">Crear</button>
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button data-toggle="modal" data-target="#supplierModal" class="btn btn-danger">Cancel</button>
            </div>
        </div>
    </div>
</div>
@*-------------- Add New MODAL END--------------------------*@

@*-------------- Suppliers List START--------------------------*@


<table class="table table-striped table-bordered" id="suppliers">
    <thead></thead>

    <tbody></tbody>


</table>

@*-------------- Suppliers List END--------------------------*@

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

@Scripts.Render("~/bundles/lib")
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@Scripts.Render("~/bundles/index")
@Scripts.Render("~/bundles/InactiveSup")